# Generated by Django 5.0.6 on 2024-06-04 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_practicalwork_file_lecturematerial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicalworksubmission',
            name='grade',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='practicalworksubmission',
            unique_together={('practical_work', 'student')},
        ),
    ]
