# Generated by Django 5.0.6 on 2024-06-04 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_practicalworksubmission_grade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicalwork',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
