# Generated by Django 5.0.6 on 2024-06-04 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_practicalwork_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicalworksubmission',
            name='grade_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='practicalworksubmission',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='graded_practicals', to=settings.AUTH_USER_MODEL),
        ),
    ]
