# Generated by Django 5.0.6 on 2024-06-04 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_practicalworksubmission_grade_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicalwork',
            name='max_score',
            field=models.FloatField(default=10.0),
        ),
    ]
